version: "3.9"

services:
  flask:
    build: ./
    restart: always
    volumes:
      - ./:/app
    command: gunicorn app:app

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - flask
    restart: always
